export const COLORS = {
    primary:{
        brown:'#3C1404',
        black:'#000000',
        white:'#FFFFFF'
    },
    secondary:{
        darkGray:'#545454',
        metal:'#979797',
        gray:'#B9BABB',
        medium:'#D5D6D8',
        light:'#EEEEEE',
        lightness:'#F4F4F4',
        shine:'#FAFAFA',
        red:'#FF647C',
        lightRed:'#FFF2F9',
        yellow:'#FFB800',
        lightYell:'#FFF9DE',
        green:'#3BC171',
        lightGreen:'#EBF9F1',
        violet:'#7B61FF',
        lightViolet:'#F2EFFF',
        blue:'#007BFF',
        lightBlue:'#DBECFF',
        navLink:'#414141'
    }
}